config/routes.rb
Rails.application.routes.draw do
  resources :posts do
    resources :comments
  end
  devise_for :users
  resources :todos do 
    member do
      patch :complete
      patch :incomplete
    end
  end
  resources :users, only: [:index, :edit, :show, :update]
  get 'home/index'
  get 'home/activity'
  root 'home#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/todo.rb
class Todo < ApplicationRecord
  # validates :content,  presence: true, length: { :minimum => 5 }
  
  has_rich_text :content
  belongs_to :user
  extend FriendlyId
  friendly_id :content, use: :slugged
  
  include PublicActivity::Model
  # tracked
  tracked owner: Proc.new{ |controller, model| controller.current_user }
end

app/controllers/todos_controller.rb
class TodosController < ApplicationController
  before_action :set_todo, only: [:show, :edit, :update, :destroy, :complete, :incomplete]

  # GET /todos
  # GET /todos.json
  def index
    @todos = Todo.where(user: current_user)
    # @pagy, @todos = pagy(Todo.all)
  end

  # GET /todos/1
  # GET /todos/1.json
  def show
  end

  # GET /todos/new
  def new
    @todo = Todo.new
  end

  # GET /todos/1/edit
  def edit
    authorize @todo
  end

  # POST /todos
  # POST /todos.json
  def create
    @todo = Todo.new(todo_params)
    @todo.user = current_user
    respond_to do |format|
      if @todo.save
        format.html { redirect_to action: "index", notice: 'Todo was successfully created.' }
        format.json { render :show, status: :created, location: @todo }
      else
        format.html { render :new }
        format.json { render json: @todo.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /todos/1
  # PATCH/PUT /todos/1.json
  def update
    respond_to do |format|
      if @todo.update(todo_params)
        format.html { redirect_to action: "index", notice: 'Todo was successfully updated.' }
        format.json { render :show, status: :ok, location: @todo }
      else
        format.html { render :edit }
        format.json { render json: @todo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /todos/1
  # DELETE /todos/1.json
  def destroy
    @todo.destroy
    respond_to do |format|
      format.html { redirect_to todos_url, notice: 'Todo was successfully destroyed.' }
      format.json { head :no_content }
      # format.js   { render :layout => false }
    end
  end
  
  def complete
    @todo.update_attribute(:complete, true)
    redirect_to action: "index", notice: "complete and visible!"
  end
  
  def incomplete
    @todo.update_attribute(:complete, false)
    redirect_to action: "index", notice: "incomplete and visible!"
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_todo
      @todo = Todo.friendly.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def todo_params
      params.require(:todo).permit(:content, :complete)
    end
end

app/helpers/todos_helper.rb
module TodosHelper
end

app/views/todos/_form.html.erb
<%= simple_form_for(@todo) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.label :content %>
    <%= f.rich_text_area :content %>
    <%= f.input :complete %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/todos/destroy.js.erb
$('.delete_todo').bind('ajax:success', function() {  
        $(this).closest('tr').fadeOut();
});  

app/views/todos/edit.html.erb
<h1>Editing Todo</h1>

<%= render 'form', todo: @todo %>

<%= link_to 'Show', @todo %> |
<%= link_to 'Back', todos_path %>

app/views/todos/index.html.erb
<div class="container">
  <p id="notice"><%= notice %></p>
  
  <h3>
    <div class="text-center mb-4">
      Todos
      <div class="badge badge-info">
        <%= @todos.count %>
      </div>
    </div>
  </h3>

  <table class='table'>
    <thead>
      <tr>
        <th>Content</th>
        <th>Completion status</th>
        <th>Action</th>
        <th>User</th>
        <th colspan="3"></th>
      </tr>
    </thead>
  
    <tbody>
      <% @todos.each do |todo| %>
          <tr>
            <td><%= todo.content %></td>
            <td>
              <% if todo.complete %>
                <span class="badge badge-success">completed</span>
              <% else %>
                <span class="badge badge-warning">incomplete</span>
              <%end%>
       
            </td>
            <td>
              <% if todo.complete %>
                <%= link_to 'incomplete', incomplete_todo_path(todo), method: :patch, class: 'btn btn-sm btn-danger'%>
              <% else %>
                <%= link_to 'complete', complete_todo_path(todo), method: :patch, class: 'btn btn-sm btn-success'%>
              <%end%>            
            </td>
            <td><%= todo.user %></td>
            <td>
              <!-- Button trigger modal -->
              <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#exampleModal">
                Detail
              </button>
              
              <!-- Modal -->
              <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
                <div class="modal-dialog">
                  <div class="modal-content">
                    <div class="modal-header">
                      <h5 class="modal-title" id="exampleModalLabel">Todo</h5>
                      <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                      </button>
                    </div>
                    <div class="modal-body">
                        <p>
                          <strong>Content:</strong>
                          <%= todo.content %>
                        </p>
                        
                        <p>
                          <strong>Complete:</strong>
                          <%= todo.complete %>
                        </p>
                    </div>
                    <div class="modal-footer">
                      <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                    </div>
                  </div>
                </div>
              </div>
            </td>
            <td><%= link_to 'Edit', edit_todo_path(todo) %></td>
            <td>
              <%= link_to '<i class="fa fa-trash" style="font-size:24px"></i>'.html_safe, todo, method: :delete, :remote => true, :class => 'delete_todo' %>
            </td>
          </tr>
        <% end %>
    </tbody>
  </table>
  
  <br>
  
  <%= link_to 'Create Todo', new_todo_path, class: 'btn btn-primary mb-3' %>
</div>

app/views/todos/new.html.erb
<h1>New Todo</h1>

<%= render 'form', todo: @todo %>

<%= link_to 'Back', todos_path %>

app/views/todos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Content:</strong>
  <%= @todo.content %>
</p>

<p>
  <strong>Complete:</strong>
  <%= @todo.complete %>
</p>

<%= link_to 'Edit', edit_todo_path(@todo) %> |
<%= link_to 'Back', todos_path %>