config/routes.rb
Rails.application.routes.draw do
  resources :posts do
    resources :comments
  end
  devise_for :users
  resources :todos do 
    member do
      patch :complete
      patch :incomplete
    end
  end
  resources :users, only: [:index, :edit, :show, :update]
  get 'home/index'
  get 'home/activity'
  root 'home#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/layouts/_footer.html.erb
<footer class="page-footer font-small blue pt-4 mt-4">
  <!-- Footer Links -->
  <div class="container-fluid text-center text-md-left">
    <!-- Grid row -->
    <div class="row">
      <!-- Grid column -->
      <div class="col-md-6 mt-md-0 mt-3">
        <!-- Content -->
        <h5 class="text-uppercase">Footer Content</h5>
        <p>Here you can use rows and columns to organize your footer content.</p>
      </div>
      <!-- Grid column -->
      <hr class="clearfix w-100 d-md-none pb-3">
      <!-- Grid column -->
      <div class="col-md-3 mb-m-0 mb-3">
        <!-- Links -->
        <h5 class="text-uppercase">Links</h5>
        <ul class="list-unstyled">
          <li>
            <a href="#!">Link 1</a>
          </li>
          <li>
            <a href="#!">Link 2</a>
          </li>
          <li>
            <a href="#!">Link 3</a>
          </li>
          <li>
            <a href="#!">Link 4</a>
          </li>
        </ul>
      </div>
      <!-- Grid column -->
      <!-- Grid column -->
      <div class="col-md-3 mb-md-0 mb-3">
        <!-- Links -->
        <h5 class="text-uppercase">Links</h5>
        <ul class="list-unstyled">
          <li>
            <a href="#!">Link 1</a>
          </li>
          <li>
            <a href="#!">Link 2</a>
          </li>
          <li>
            <a href="#!">Link 3</a>
          </li>
          <li>
            <a href="#!">Link 4</a>
          </li>
        </ul>
      </div>
      <!-- Grid column -->
    </div>
    <!-- Grid row -->
  </div>
  <!-- Footer Links -->
  <!-- Copyright -->
  <div class="footer-copyright text-center py-3">© 2020 Copyright:
    <a href="https://tom-issarakoat.web.app/"> Tom Issarakoat</a>
  </div>
  <!-- Copyright -->
</footer>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <%= link_to root_path, class: 'btn btn-success' do %>
    <i class="fas fa-home"></i>
  <% end %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <% if current_user %>
      <ul class="navbar-nav mr-auto">
        <li class="nav-item">
          <a class="nav-link" href="#">About</a>
        </li>
        <% if current_user && current_user.has_role?(:admin) %>
          <li class="<%= 'active font-weight-bold' if current_page?(users_path) %> nav-item">
            <%= link_to users_path, class: 'nav-link' do %>
              <div class="fa fa-users"></div>
              Users
            <% end %>
        <% end %>
        </li>
        <li class="<%= 'active font-weight-bold' if current_page?(home_activity_path) %> nav-item">
          <%= link_to home_activity_path, class: 'nav-link' do %>
            <div class="fa fa-bell"></div>
            Activity
          <% end %>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            Projects
          </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdown">
            <%= link_to todos_path, class: 'dropdown-item' do %>
              Todo List
            <% end %>
            <%= link_to posts_path, class: 'dropdown-item' do %>
              Posts
            <% end %>
          </div>
        </li>
      </ul>
      
    <!--search stuff-->
    <!--<div class="form-inline my-2 my-lg-0">-->
    <!--  <%= form_tag(todos_path, method: :get) do %>-->
    <!--    <div class="input-group">-->
    <!--      <%= text_field_tag :content, params[:content], autocomplete: 'off', placeholder: "Search todo", class: 'form-control-sm' %>-->
    <!--      <span class="input-group-append">-->
    <!--        <button class="btn btn-primary btn-sm" type="submit">-->
    <!--          <span aria-hidden="true" class="fa fa-search"></span>-->
    <!--        </button>-->
    <!--      </span>-->
    <!--    </div>-->
    <!--  <% end %>-->
    <!--</div>-->
      <!--user stuff-->
      <ul class="navbar-nav mr-right">
        <li class="nav-item dropdown">
          <a aria-expanded="false" aria-haspopup="true" class="nav-link dropdown-toggle" data-toggle="dropdown" href="#" id="navbarDropdown" role="button">
            <b>
              <%= current_user.email %>
            </b>
          </a>
          <div aria-labelledby="navbarDropdown" class="dropdown-menu dropdown-menu-right">
            <%= link_to edit_user_registration_path, class: "dropdown-item" do %>
              <div class="fa fa-cog"></div>
              <b>Account settings</b>
            <% end %>
            <%= link_to destroy_user_session_path, method: :delete, class: "dropdown-item" do %>
              <div class="fa fa-sign-out-alt"></div>
              <b>Sign out</b>
            <% end %>
          </div>
        </li>
      </ul>
    <% else %>
      <ul class="navbar-nav mr-auto"></ul>
      <ul class="navbar-nav mr-right">
        <li class="<%= 'active font-weight-bold' if current_page?(new_user_registration_path) %> nav-item">
          <%= link_to 'Sign Up', new_user_registration_path, class: 'nav-link' %>
        </li>
        <li class="<%= 'active font-weight-bold' if current_page?(new_user_session_path) %> nav-item">
          <%= link_to 'Log In', new_user_session_path, class: 'nav-link' %>
        </li>
      </ul>
    <% end %>
  </div>
</nav>

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name.to_s == 'notice' ? 'success' : 'danger' %>" role="alert">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
        <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Rubyapp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/header' %>
    <%= render 'layouts/messages' %>
    
    <div class='container'>
      <%= yield %>
    </div>
    <div class="bg-dark text-white">
      <%= render 'layouts/footer' %>
    </div>
  </body>
</html>